<?php
    $home_class = Index::__GetPage()=='userhome' ? 'active':'';
    $students_class = Index::__GetPage()=='manage-students' ? 'active':'';
?>


<div class="navbar-collapse collapse" style="height: 1px;">
    <ul class="nav navbar-nav navbar-right">
        <li class="<?php echo $home_class; ?>">
            <a class="<?php  ?>" href="<?php echo UI::GetPageUrl('home') ?>">Home</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">My courses <span class="caret"></span></a>
            <ul class="dropdown-menu navbar-default">
                <li><a href="<?php echo UI::GetPageUrl('course-form') ?>">Create course</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">No existing course</li>
            </ul>
        </li>
        <li class="<?php echo $students_class ?>">
            <a href="<?php echo UI::GetPageUrl('manage-students') ?>">My students</a></li>
    </ul>
</div><!--/.nav-collapse -->