<div class="navbar-collapse collapse" style="height: 1px;">
    <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="#">Home</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">My subjects <span class="caret"></span></a>
            <ul class="dropdown-menu navbar-default">
                <li><a href="#">Create subject</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Subjects list</li>
                <li><a href="#">Create subject</a></li>
                <li><a href="#">Create subject</a></li>
            </ul>
        </li>
        <li><a href="#students">Students</a></li>
    </ul>
</div><!--/.nav-collapse -->