<div class="row">
    <div class="col-lg-6 col-md-6">
        <h3>User panel</h3>
    </div>
    <div class="col-lg-6 col-md-6" align="right">
        <br>
        <div class="btn-group" align="left">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                <span class="glyphicon glyphicon-user"></span>
                &nbsp;&nbsp;<?php echo USER::Get(USER::USERNAME) ?>
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
                <li><a href="<?php echo UI::GetPageUrl('logout') ?>">Logout</a></li>
            </ul>
        </div>
    </div>
</div>