<html>
    <head>
        <!-- Metadata -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Your description falls here">
        <meta name="author" content="Allen Linatoc, Imari Elanor Malabanan, Patricia Mae Marasigan">

        <link rel="stylesheet" href="web+/bootstrap/css/bootstrap.css">
        <link rel="stylesheet" href="web+/bootstrap/css/bootstrap-theme.css">

        <!-- Site components -->
        <link rel="stylesheet" href="web+/site/css/default.css">
        <link rel="stylesheet" href="web+/site/css/header.css">
        <link rel="stylesheet" href="web+/site/css/footer.css">

        <title><?php echo PARAMS::Get('header_title'); ?></title>
    </head>
    <body role="document">
        <header class="navbar navbar-default navbar-fixed-top" role="navigation">
            <!-- Put your HEADER Contents here!!! -->
            <div class="container">
                <!-- Title stuff here -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo UI::GetPageUrl('home') ?>">FOGS</a>
                </div>
                
                <!-- Navigation stuff here -->
                <?php
                if ( USER::__IsLoggedIn() )
                {
                    Index::__IncludeFiles('page/_includes', [
                        'nav_user.phtml'
                    ]);
                }
                ?>
                
            </div>
        </header>