<html>
    <head>
        <!-- Metadata -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Your description falls here">
        <meta name="author" content="Allen Linatoc, Imari Elanor Malabanan, Patricia Mae Marasigan">

        <!-- Bootstrap components -->
        <script type="text/javascript" src="web+/bootstrap/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="web+/bootstrap/css/bootstrap.css">

        <!-- Site components -->
        <link rel="stylesheet" href="web+/site/css/default.css">
        <link rel="stylesheet" href="web+/site/css/header.css">
        <link rel="stylesheet" href="web+/site/css/footer.css">

        <title><?php echo PARAMS::Get('header_title'); ?></title>
    </head>
    <body class="row-fluid">
        <header class="row-fluid">
            <!-- Put your HEADER Contents here!!! -->
            <div style="background-color:#13007D; color:#fff; padding:3%;">
                Your header is here!
            </div>
        </header>