        </div>
    </div>
    <br>
    <br>
    <footer class="navbar navbar-inverse navbar-fixed-bottom" id="footer">
        <!-- Put your HEADER Contents here!!! -->
        <div class="container navbar-text">
            A course project by
            <a href="javascript:;">Allen Linatoc</a>, 
            <a href="javascript:;">Imari Elanor Malabanan</a> and 
            <a href="javascript:;">Patricia Mae Marasigan</a>
        </div>
    </footer>

    <!-- jQuery scripts here -->
    <script type="text/javascript" src="web+/jquery/js/jquery.min.js"></script>
    
    <!-- Bootstrap components -->
    <script type="text/javascript" src="web+/bootstrap/js/bootstrap.js"></script>
    
    <!-- APHP framework scripts -->
    <script type="text/javascript" src="web+/aphp/js/flash.js"></script>
</body>
</html>