        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        </div>
    </div>
    <footer class="navbar navbar-inverse navbar-fixed-bottom" id="footer">
        <!-- Put your HEADER Contents here!!! -->
        <div class="container navbar-text">
            A course project by
            <a href="javascript:;">Allen Linatoc</a>, 
            <a href="javascript:;">Imari Elanor Malabanan</a> and 
            <a href="javascript:;">Patricia Mae Marasigan</a>
        </div>
    </footer>
    
    <!-- Bootstrap components -->
    <script type="text/javascript" src="web+/bootstrap/js/bootstrap.js"></script>
    
</body>
</html>