<div class="container">
    <div class="jumbotron" role="main">
        <br>
        <br>
        <h4 align="center">Welcome to FAITH Online Grading System</h4>
        <br>
        <div align="center" class="row-fluid">
            <br>
            <form role="form" method="post">
                <div align="center" class="row">
                    <div class="col-lg-7 col-md-7">
                        Log in to your account
                    </div>
                </div>
                <br>
                <div class="input-group center col-lg-7 col-md-7">
                    <span class="input-group-addon">Username</span>
                    <input 
                        type=           "text"
                        name=           "postUsername"
                        class=          "form-control" 
                        maxlength=      "30" 
                        placeholder=    "Username here" 
                        required=       "required">
                </div>
                <br>
                <div class="input-group center col-lg-7 col-md-7">
                    <span class="input-group-addon">Password</span>
                    <input
                        type=           "password"
                        name=           "postPassword"
                        class=          "form-control"
                        maxlength=      "30"
                        placeholder=    "Your password"
                        required=       "required">
                </div>
                <br>
                <div class="row btn-group" align="center">
                    <button class="btn btn-primary">Login</button>
                    <button class="btn btn-warning">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>