<div style="padding: 5%">
    Welcome to your first homepage!
    <br>
    <br>
    You can change the page contents at <b><i>page/home.phtml</i></b>
    <br>
    You can also set the back-end script at <b><i>page/home.php</i></b>
    <br>
    <br>
    Some of the startup tasks you can do around:
    <ul>
        <li>Add new pages at <b>page</b> folder</li>
        <li>New pages should be registered at <b>config/pages.ini</b></li>
        <li>Every page consists of 2 files: Back-end script (.php) and the Front-end script (.phtml)</li>
    </ul>
    
</div>