<script type="text/javascript" language="Javascript">
    // always hover to the form
    $(document).ready(function() {
        scrollTo('div#form_student')
    });
</script>
<br>
<br>
<?php
define('PANEL_TITLE', 'Manage students');
Index::__IncludeFiles('page/_includes', [ 'panel_header.phtml' ], false);
?>

<hr class="hr-default">
<div class="row-fluid">
    <?php
    if ( $MODE!=='ADD' && $MODE!=='EDIT' )
    {
        UI::Button('Add new', 'button', 'btn btn-primary'
                , UI::GetPageUrl(Index::__GetPage(), array(
                    'MODE' => 'ADD')));
    }
    else
    {
        require 'page/_includes/form_student.phtml';
    }
    ?>
</div>
<hr class="hr-default">
<div class="row-fluid">
    <div class="panel panel-success">
        <div class="panel-heading"><span class="glyphicon glyphicon-record"></span>  <b>Students</b></div>
        <?php
        $report_Students->renderReport();
        ?>
    </div>
</div>
