<br>
<br>
<?php
define('PANEL_TITLE', 'User panel');
Index::__IncludeFiles('page/_includes', [ 'panel_header.phtml' ], false);
?>
<hr class="hr-default">

<!-- Main contents here -->

<div class="container">
    <div class="container-fluid" align="center">
        <div class="col-lg-6 col-md-6">
            <ul class="list-group" align="left">
                <a href="<?php echo UI::GetPageUrl('manage-students') ?>" class="list-group-item">
                    <span class="badge"><?php echo $count_Students ?></span>
                    Manage students
                </a>
                <a href="<?php echo UI::GetPageUrl('manage-courses') ?>" class="list-group-item">
                    <span class="badge"><?php echo $count_Courses ?></span>
                    Manage courses
                </a>
            </ul>
        </div>
    </div>
</div>